#!/usr/bin/env python3
# Pull nuxd's AndroidManifest.xml (a `combined` NON-footprint environment), rewrite its package name to
# com.meta.shell.env.footprint.haven2025, and HARDCODE the finished AXML into src/cook/nuxd_manifest_axml.h.
# The cook uses these bytes verbatim (no runtime patchAxml) so an unrooted user replaces the haven2025 package
# but the shell reads a plain combined Environment -> no footprint, no vista. [[project_hsr_unrooted_footprint_vista_fix]]
import os, struct, zipfile

NUXD = r"D:\Quest Stuff\Restore Old Envs\Envs To check\v203 Ufficial Envs\Nuxd.apk"
OUT  = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "cook", "nuxd_manifest_axml.h")
OLD  = "com.meta.environment.prod.nuxd"
NEW  = "com.meta.shell.env.footprint.haven2025"

d = bytearray(zipfile.ZipFile(NUXD).read("AndroidManifest.xml"))

# ── AXML string-pool package rewrite (port of the C++ patchAxml; substring replace on every pooled string) ──
assert struct.unpack_from("<H", d, 0)[0] == 3, "not AXML"
sp = 8
assert struct.unpack_from("<H", d, sp)[0] == 1, "no string pool"
sp_hdr   = struct.unpack_from("<H", d, sp+2)[0]
sp_size  = struct.unpack_from("<I", d, sp+4)[0]
strCount = struct.unpack_from("<I", d, sp+8)[0]
styleCount = struct.unpack_from("<I", d, sp+12)[0]
flags    = struct.unpack_from("<I", d, sp+16)[0]
stringsStart = struct.unpack_from("<I", d, sp+20)[0]
utf8 = (flags & 0x100) != 0
off0  = sp + sp_hdr
sbase = sp + stringsStart

def read_str(p):
    if utf8:
        n = d[p]; p += 1
        if n & 0x80: p += 1
        bl = d[p]; p += 1
        if bl & 0x80: bl = ((bl & 0x7f) << 8) | d[p]; p += 1
        return d[p:p+bl].decode('utf-8', 'replace')
    else:
        l = struct.unpack_from("<H", d, p)[0]; p += 2
        if l & 0x8000: l = ((l & 0x7fff) << 16) | struct.unpack_from("<H", d, p)[0]; p += 2
        return d[p:p+2*l].decode('utf-16-le', 'replace')

strings = []
for i in range(strCount):
    o = struct.unpack_from("<I", d, off0 + i*4)[0]
    strings.append(read_str(sbase + o))

nrepl = sum(OLD in s for s in strings)
new_strings = [s.replace(OLD, NEW) for s in strings]

def enc_len(n, out):
    if n < 0x80: out.append(n)
    else: out += bytes([0x80 | (n >> 8), n & 0xff])

data = bytearray(); noff = []
for s in new_strings:
    noff.append(len(data))
    if utf8:
        b = s.encode('utf-8'); enc_len(len(s), data); enc_len(len(b), data); data += b; data.append(0)
    else:
        data += struct.pack("<H", len(s))            # UTF-16: u16 char-count prefix (NOT the utf8 varint)
        data += s.encode('utf-16-le')                # chars
        data += b"\x00\x00"                          # u16 null terminator
while len(data) % 4: data.append(0)

off_arr = b"".join(struct.pack("<I", o) for o in noff)
style_arr = bytes(d[off0 + strCount*4 : sbase])   # style offsets + any pad (usually empty)
new_stringsStart = sp_hdr + len(off_arr) + len(style_arr)

body = bytearray()
body += struct.pack("<IIIII", strCount, styleCount, flags, new_stringsStart, 0)
body += off_arr + style_arr + data
new_sp_size = 8 + len(body)

out = bytearray(d[:8])
out += struct.pack("<HH", 1, sp_hdr) + struct.pack("<I", new_sp_size) + body
out += d[sp + sp_size:]                    # everything after the string pool (chunks index strings by INDEX -> valid)
struct.pack_into("<I", out, 4, len(out))   # fix total file size

# ── verify: re-read the string pool of the rewritten AXML; NEW present, OLD gone, structure valid ──
def pool_strings(buf):
    sp2 = 8; hdr = struct.unpack_from("<H", buf, sp2+2)[0]
    sc = struct.unpack_from("<I", buf, sp2+8)[0]; fl = struct.unpack_from("<I", buf, sp2+16)[0]
    ss = struct.unpack_from("<I", buf, sp2+20)[0]; u8 = (fl & 0x100)!=0; o0 = sp2+hdr; sb = sp2+ss
    res = []
    for i in range(sc):
        p = sb + struct.unpack_from("<I", buf, o0+i*4)[0]
        if u8:
            n=buf[p];p+=1
            if n&0x80:p+=1
            bl=buf[p];p+=1
            if bl&0x80:bl=((bl&0x7f)<<8)|buf[p];p+=1
            res.append(buf[p:p+bl].decode('utf-8','replace'))
        else:
            l=struct.unpack_from("<H",buf,p)[0];p+=2
            if l&0x8000:l=((l&0x7fff)<<16)|struct.unpack_from("<H",buf,p)[0];p+=2
            res.append(buf[p:p+2*l].decode('utf-16-le','replace'))
    return res

rt = pool_strings(out)
assert NEW in rt, "haven2025 package string not in rewritten pool"
assert not any(OLD == s for s in rt), "nuxd package string still present"
assert struct.unpack_from("<I", out, 4)[0] == len(out), "file size mismatch"
print("replaced %d pooled strings; pool now has %r, no bare %r; %d -> %d bytes" % (nrepl, NEW, OLD, len(d), len(out)))
print("  combined:", "combined" in rt, "| standalone 'footprint':", "footprint" in rt,
      "| NullService:", [s for s in rt if "NullService" in s])

hdr = ["// AUTO-GENERATED by cooker/gen_haven_combined_manifest.py -- do not edit.",
       "// nuxd's AndroidManifest.xml (a `combined` NON-FOOTPRINT environment) with the package name rewritten to",
       "// com.meta.shell.env.footprint.haven2025 and HARDCODED here. The spoof cook uses these bytes verbatim: an",
       "// unrooted user replaces the haven2025 package, but the shell reads a plain combined Environment -> no",
       "// footprint, no vista. [[project_hsr_unrooted_footprint_vista_fix]]",
       "#pragma once", "#include <cstddef>",
       "static const unsigned char NUXD_MANIFEST_AXML[] = {"]
line = "  "
for bb in out:
    line += "%d," % bb
    if len(line) > 110: hdr.append(line); line = "  "
if line.strip(): hdr.append(line)
hdr.append("};")
hdr.append("static const size_t NUXD_MANIFEST_AXML_LEN = %d;" % len(out))
open(OUT, "w", newline="\n").write("\n".join(hdr) + "\n")
print("wrote", OUT)
