#!/usr/bin/env python3
# Generates src/cook/haven_stock_templates.h — the stock haven2025 TEMPLATE closure (JSON hstf files only,
# no geometry/textures) with their EXACT stock manifest keys (pkg/ing StringIds Meta computed).
#
# WHY (TheMysticle logcat 2026-07-10): on UNROOTED devices the shell loads the haven2025 spoof as a
# FOOTPRINT and force-pairs a companion VISTA (calming/focused — shell-config-driven, the APK manifest's
# "combined" flip is ignored on that path). The vista's own templates (home_w_calming_lm.hstf etc.) nest
# stock home_c25 templates by StringId key — our cooked scene.zip replaced them, so the vista load died
# with ErrorFileNotFound and the shell rejected the WHOLE pair -> nuxd fallback ("home gets rejected").
# Shipping the stock template closure (any nested template resolves; their mesh/texture refs stay absent
# = proven-non-fatal invisible) makes ANY companion vista load, so the cooked footprint is accepted.
#
# Usage: python gen_haven_stock_templates.py [path/to/stock/haven2025.apk]
import io, os, re, struct, sys, zipfile, zlib

APK = sys.argv[1] if len(sys.argv) > 1 else r"D:\Quest Stuff\Restore Old Envs\Envs To check\v203 Ufficial Envs\haven2025.apk"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "cook", "haven_stock_templates.h")
TGT_TEMPLATE = 2719744159
HOME_PKG = 12293612625969361106  # StringId("meta/home_c25") — stock, matches the vista's cross-package refs

z = zipfile.ZipFile(io.BytesIO(zipfile.ZipFile(APK).read("assets/scene.zip")))
b = z.read("content/assets.manifest")

# ── minimal ASMH (FlatBuffers) reader ──
def toffs(pos):
    vt = pos - struct.unpack_from("<i", b, pos)[0]
    n = (struct.unpack_from("<H", b, vt)[0] - 4) // 2
    return struct.unpack_from("<%dH" % n, b, vt + 4)
def uoff(pos): return pos + struct.unpack_from("<I", b, pos)[0]
def vec(pos):
    n = struct.unpack_from("<I", b, pos)[0]
    return [pos + 4 + 4 * i + struct.unpack_from("<i", b, pos + 4 + 4 * i)[0] for i in range(n)]
def fstr(pos):
    n = struct.unpack_from("<I", b, pos)[0]
    return b[pos + 4:pos + 4 + n].decode()

root = 16 + struct.unpack_from("<I", b, 16)[0]
ro = toffs(root)
entries = []           # (pkg, ing, tgt, zipPath)
for p in vec(uoff(root + ro[7])):
    eo = toffs(p)
    pkg, ing, tgt = struct.unpack_from("<QQI", b, p + eo[0])
    entries.append((pkg, ing, tgt, fstr(uoff(p + eo[1]))))
relstr = {}            # ing hash -> ORIGINAL-CASE relPath string (field3 map; zip paths are lowercased)
for p in vec(uoff(root + ro[3])):
    eo = toffs(p)
    relstr[struct.unpack_from("<Q", b, p + eo[0])[0]] = fstr(uoff(p + eo[1]))

tpl = {ing: path for pkg, ing, tgt, path in entries if tgt == TGT_TEMPLATE and pkg == HOME_PKG}
# closure seeded from the templates/ dir files (the ones vistas nest), following template->template refs
seeds = [ing for ing, path in tpl.items() if "/templates/" in path]
seen, stack, out = set(seeds), list(seeds), []
REF = re.compile(r'"packageOrRemoteId":\s*"(\d+)",\s*"ingestionId":\s*"(\d+)",\s*"targetId":\s*(\d+)')
while stack:
    ing = stack.pop()
    data = z.read("content/" + tpl[ing])
    out.append((relstr[ing], ing, data))
    for m in REF.finditer(data.decode()):
        if int(m.group(1)) == HOME_PKG and int(m.group(3)) == TGT_TEMPLATE:
            i2 = int(m.group(2))
            if i2 in tpl and i2 not in seen: seen.add(i2); stack.append(i2)
out.sort()

blob = bytearray(); table = []
for rel, ing, data in out:
    table.append((rel, ing, len(blob), len(data))); blob += data
comp = zlib.compress(bytes(blob), 9)
print("closure: %d templates, %d bytes raw, %d compressed" % (len(out), len(blob), len(comp)))

with open(OUT, "w", newline="\n") as h:
    h.write("// AUTO-GENERATED by cooker/gen_haven_stock_templates.py — do not edit.\n"
            "// Stock haven2025 TEMPLATE closure (JSON only) with Meta's exact manifest StringIds, so a cooked\n"
            "// haven2025 spoof loaded as a FOOTPRINT satisfies any companion VISTA's nested home_c25 template\n"
            "// refs (unrooted devices force-pair a vista; a missing nested template rejects the WHOLE env).\n"
            "#pragma once\n#include <vector>\n#include <string>\n#include <cstdint>\n#include <mutex>\n"
            "#include \"miniz.h\"\n"
            "namespace havenstock {\n"
            "struct Tpl { const char* relPath; uint64_t ing; unsigned off, len; };\n"
            "static const uint64_t HOME_PKG = %dull;   // StringId(\"meta/home_c25\")\n" % HOME_PKG)
    h.write("static const unsigned char ZBLOB[]={" + ",".join(str(x) for x in comp) + "};\n")
    h.write("static const unsigned ZLEN=%d, RAWLEN=%d;\n" % (len(comp), len(blob)))
    h.write("static const Tpl TBL[]={" + ",".join('{"%s",%dull,%d,%d}' % t for t in table) + "};\n")
    h.write("static const unsigned NTBL=%d;\n" % len(table))
    h.write(
        "// relPath (stock-cased, e.g. \"templates/Quest3/home_props.hstf\") + ing StringId + file bytes.\n"
        "inline const std::vector<std::pair<const Tpl*, std::vector<uint8_t>>>& templates() {\n"
        "    static std::vector<std::pair<const Tpl*, std::vector<uint8_t>>> r; static std::once_flag once;\n"
        "    std::call_once(once, [](){ std::vector<uint8_t> raw(RAWLEN); mz_ulong dl=RAWLEN;\n"
        "        mz_uncompress(raw.data(), &dl, ZBLOB, ZLEN);\n"
        "        for (unsigned i=0;i<NTBL;i++) r.push_back({ &TBL[i], std::vector<uint8_t>(raw.begin()+TBL[i].off, raw.begin()+TBL[i].off+TBL[i].len) }); });\n"
        "    return r;\n"
        "}\n"
        "} // namespace havenstock\n")
print("wrote", OUT)
